scan_filter_chain:
- name: box
  type: LaserScanBoxNoiserFilter
  params:
    box_frame: map
    min_x: -12
    max_x: -8
    min_y: 5.8
    max_y: 9.8
    min_z: -1.0
    max_z: 2.0
    mean:  0.0
    stddev: 1.0